_format_version: '2.1'
_transform: true

###
### Consumers / Users
###
consumers:
  - username: DASHBOARD
  - username: anon
    keyauth_credentials:
      - key: $SUPABASE_ANON_KEY
  - username: service_role
    keyauth_credentials:
      - key: $SUPABASE_SERVICE_KEY

###
### Access Control List
###
acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

###
### API Routes
###
services:
  ## Open Auth routes
  - name: auth-v1-open-token
    _comment: 'GoTrue Token: /auth/v1/token -> http://auth:9999/token (public access for signin and token refresh)'
    url: http://auth:9999/token
    routes:
      - name: auth-v1-open-token
        strip_path: true
        paths:
          - /auth/v1/token
        regex_priority: 100
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
            - "http://localhost:8000"
            - "http://127.0.0.1:8000"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS

  ## Protected Dashboard - catch all remaining routes
  - name: dashboard
    _comment: 'Studio: /* -> http://studio:3000/*'
    url: http://studio:3000/
    routes:
      - name: dashboard-all
        strip_path: true
        paths:
          - /
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
            - "http://localhost:8000"
            - "http://127.0.0.1:8000"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS