/**
 * @vitest-environment node
 */
import { describe, expect, it, beforeEach, afterEach, vi } from 'vitest'
import { 
  getConnectionStrings,
  validateAutoGeneratedCredentials,
  generateEnhancedConnectionStrings,
  validateConnectionStringFormat,
  validateParameterSubstitution
} from './DatabaseSettings.utils'

describe('Enhanced Connection String Generation with Auto-Generated Credentials', () => {
  const originalEnv = process.env

  beforeEach(() => {
    vi.resetModules()
    process.env = { ...originalEnv }
  })

  afterEach(() => {
    process.env = originalEnv
  })

  describe('getConnectionStrings with auto-generated credentials', () => {
    it('should generate connection strings with auto-generated database name and user', () => {
      const connectionInfo = {
        db_user: 'proj_myproject_abc123_def456',
        db_port: 5432,
        db_host: 'localhost',
        db_name: 'myproject_xyz789_ghi012'
      }

      const result = getConnectionStrings({
        connectionInfo,
        metadata: { projectRef: 'test-project' },
        revealPassword: false,
        actualPassword: 'test-password'
      })

      // Requirements 2.1, 2.2, 2.3: Verify connection strings contain auto-generated credentials
      expect(result.direct.uri).toContain('proj_myproject_abc123_def456')
      expect(result.direct.uri).toContain('myproject_xyz789_ghi012')
      expect(result.direct.uri).toContain('localhost:5432')
      expect(result.direct.uri).toMatch(/^postgresql:\/\//)
    })

    it('should handle password visibility correctly with auto-generated credentials', () => {
      const connectionInfo = {
        db_user: 'proj_testapp_random123',
        db_port: 5432,
        db_host: 'db.example.com',
        db_name: 'testapp_db_456789'
      }

      // Test with hidden password
      const hiddenResult = getConnectionStrings({
        connectionInfo,
        metadata: { projectRef: 'test-project' },
        revealPassword: false,
        actualPassword: 'secret123'
      })

      expect(hiddenResult.direct.uri).toContain('[YOUR_PASSWORD]')
      expect(hiddenResult.direct.uri).not.toContain('secret123')

      // Test with revealed password
      const revealedResult = getConnectionStrings({
        connectionInfo,
        metadata: { projectRef: 'test-project' },
        revealPassword: true,
        actualPassword: 'secret123'
      })

      expect(revealedResult.direct.uri).toContain('secret123')
      expect(revealedResult.direct.uri).not.toContain('[YOUR_PASSWORD]')
    })

    it('should generate pooler connection strings with auto-generated credentials', () => {
      const connectionInfo = {
        db_user: 'proj_webapp_xyz123',
        db_port: 5432,
        db_host: 'localhost',
        db_name: 'webapp_db_abc456'
      }

      const poolingInfo = {
        connectionString: 'postgresql://proj_webapp_xyz123:password@pooler.example.com:6543/webapp_db_abc456',
        db_user: 'proj_webapp_xyz123',
        db_port: 6543,
        db_host: 'pooler.example.com',
        db_name: 'webapp_db_abc456'
      }

      const result = getConnectionStrings({
        connectionInfo,
        poolingInfo,
        metadata: { projectRef: 'test-project' },
        revealPassword: true,
        actualPassword: 'test-password'
      })

      // Requirements 2.1, 2.2, 2.3: Verify pooler connection strings contain auto-generated credentials
      // The pooler URI should be the modified connectionString with password replacement
      expect(result.pooler.uri).toContain('test-password')
      expect(result.pooler.uri).toContain('webapp_db_abc456')
      expect(result.pooler.uri).toContain('pooler.example.com:6543')
    })
  })

  describe('validateAutoGeneratedCredentials', () => {
    it('should validate connection string with correct auto-generated credentials', () => {
      const connectionString = 'postgresql://proj_myapp_abc123:password@localhost:5432/myapp_db_xyz789'
      const expectedCredentials = {
        user: 'proj_myapp_abc123',
        database: 'myapp_db_xyz789',
        host: 'localhost',
        port: 5432
      }

      const result = validateAutoGeneratedCredentials(connectionString, expectedCredentials)
      expect(result).toBe(true)
    })

    it('should reject connection string with incorrect auto-generated user', () => {
      const connectionString = 'postgresql://wrong_user:password@localhost:5432/myapp_db_xyz789'
      const expectedCredentials = {
        user: 'proj_myapp_abc123',
        database: 'myapp_db_xyz789',
        host: 'localhost',
        port: 5432
      }

      const result = validateAutoGeneratedCredentials(connectionString, expectedCredentials)
      expect(result).toBe(false)
    })

    it('should reject connection string with incorrect auto-generated database', () => {
      const connectionString = 'postgresql://proj_myapp_abc123:password@localhost:5432/wrong_database'
      const expectedCredentials = {
        user: 'proj_myapp_abc123',
        database: 'myapp_db_xyz789',
        host: 'localhost',
        port: 5432
      }

      const result = validateAutoGeneratedCredentials(connectionString, expectedCredentials)
      expect(result).toBe(false)
    })

    it('should handle partial credential validation', () => {
      const connectionString = 'postgresql://proj_myapp_abc123:password@localhost:5432/myapp_db_xyz789'
      
      // Test with only user validation
      const userOnlyResult = validateAutoGeneratedCredentials(connectionString, {
        user: 'proj_myapp_abc123'
      })
      expect(userOnlyResult).toBe(true)

      // Test with only database validation
      const dbOnlyResult = validateAutoGeneratedCredentials(connectionString, {
        database: 'myapp_db_xyz789'
      })
      expect(dbOnlyResult).toBe(true)
    })

    it('should handle invalid connection string format', () => {
      const invalidConnectionString = 'not-a-valid-connection-string'
      const expectedCredentials = {
        user: 'proj_myapp_abc123',
        database: 'myapp_db_xyz789'
      }

      const result = validateAutoGeneratedCredentials(invalidConnectionString, expectedCredentials)
      expect(result).toBe(false)
    })
  })

  describe('generateEnhancedConnectionStrings with auto-generated credentials', () => {
    it('should generate connection strings with auto-generated credentials', () => {
      const connectionInfo = {
        db_user: 'proj_testproject_random456',
        db_port: 5432,
        db_host: 'localhost',
        db_name: 'testproject_db_789abc'
      }

      const result = generateEnhancedConnectionStrings({
        connectionInfo,
        metadata: { projectRef: 'test-project' },
        useEnvironmentDefaults: true,
        revealPassword: true,
        actualPassword: 'test-password'
      })

      // Requirements 2.1, 2.2, 2.3: Verify enhanced generation includes auto-generated credentials
      expect(result.direct.uri).toContain('proj_testproject_random456')
      expect(result.direct.uri).toContain('testproject_db_789abc')
      expect(result.direct.uri).toContain('test-password')
      expect(result.direct.uri).toContain('localhost:5432')
    })

    it('should handle basic validation with auto-generated credentials', () => {
      const connectionInfo = {
        db_user: 'proj_testproject_random456',
        db_port: 5432,
        db_host: 'db.example.com', // Use a non-localhost host to pass parameter substitution validation
        db_name: 'testproject_db_789abc'
      }

      const result = generateEnhancedConnectionStrings({
        connectionInfo,
        metadata: { projectRef: 'test-project' },
        useEnvironmentDefaults: true,
        revealPassword: true,
        actualPassword: 'test-password'
      })

      // Basic validation should pass
      expect(validateConnectionStringFormat(result.direct.uri)).toBe(true)
      expect(validateParameterSubstitution(result.direct.uri)).toBe(true)
    })

    it('should handle pooler connection strings with auto-generated credentials', () => {
      const connectionInfo = {
        db_user: 'proj_poolertest_abc123',
        db_port: 5432,
        db_host: 'localhost',
        db_name: 'poolertest_db_def456'
      }

      const poolingInfo = {
        connectionString: 'postgresql://proj_poolertest_abc123:password@pooler.localhost:6543/poolertest_db_def456',
        db_user: 'proj_poolertest_abc123',
        db_port: 6543,
        db_host: 'pooler.localhost',
        db_name: 'poolertest_db_def456'
      }

      const result = generateEnhancedConnectionStrings({
        connectionInfo,
        poolingInfo,
        metadata: { projectRef: 'test-project' },
        useEnvironmentDefaults: true,
        revealPassword: true,
        actualPassword: 'test-password'
      })

      // Requirements 2.1, 2.2, 2.3: Verify pooler strings include auto-generated credentials
      expect(result.pooler.uri).toContain('test-password')
      expect(result.pooler.uri).toContain('poolertest_db_def456')
      expect(result.pooler.uri).toContain('pooler.localhost:6543')
    })
  })

  describe('Connection string parsing with auto-generated credentials', () => {
    it('should correctly parse connection strings with auto-generated credentials', () => {
      const connectionString = 'postgresql://proj_myapp_random123_timestamp456:secret@localhost:5432/myapp_db_xyz789_timestamp456'
      
      // Parse using URL constructor (same logic as parseConnectionString)
      const url = new URL(connectionString)
      const result = {
        user: url.username || undefined,
        password: url.password || undefined,
        host: url.hostname || undefined,
        port: url.port ? parseInt(url.port, 10) : undefined,
        database: url.pathname.slice(1) || undefined,
      }

      expect(result.user).toBe('proj_myapp_random123_timestamp456')
      expect(result.password).toBe('secret')
      expect(result.host).toBe('localhost')
      expect(result.port).toBe(5432)
      expect(result.database).toBe('myapp_db_xyz789_timestamp456')
    })

    it('should handle auto-generated credentials with special characters', () => {
      const connectionString = 'postgresql://proj_my_app_test_abc123:password@db-host:5432/my_app_test_db_xyz789'
      
      const url = new URL(connectionString)
      const result = {
        user: url.username || undefined,
        password: url.password || undefined,
        host: url.hostname || undefined,
        port: url.port ? parseInt(url.port, 10) : undefined,
        database: url.pathname.slice(1) || undefined,
      }

      expect(result.user).toBe('proj_my_app_test_abc123')
      expect(result.database).toBe('my_app_test_db_xyz789')
      expect(result.host).toBe('db-host')
    })

    it('should parse connection strings with masked passwords and auto-generated credentials', () => {
      const connectionString = 'postgresql://proj_webapp_secure456:[YOUR_PASSWORD]@localhost:5432/webapp_db_secure789'
      
      const url = new URL(connectionString)
      const result = {
        user: url.username || undefined,
        password: url.password ? decodeURIComponent(url.password) : undefined,
        host: url.hostname || undefined,
        port: url.port ? parseInt(url.port, 10) : undefined,
        database: url.pathname.slice(1) || undefined,
      }

      expect(result.user).toBe('proj_webapp_secure456')
      expect(result.password).toBe('[YOUR_PASSWORD]')
      expect(result.database).toBe('webapp_db_secure789')
    })
  })

  describe('Integration with project creation workflow', () => {
    it('should generate connection strings that match project creation API output', () => {
      // Simulate auto-generated credentials from project creation
      const projectName = 'My Test Project'
      const autoGeneratedUser = 'proj_my_test_project_abc123_def456'
      const autoGeneratedDatabase = 'my_test_project_xyz789_ghi012'
      
      const connectionInfo = {
        db_user: autoGeneratedUser,
        db_port: 5432,
        db_host: 'localhost',
        db_name: autoGeneratedDatabase
      }

      const result = getConnectionStrings({
        connectionInfo,
        metadata: { projectRef: 'generated-project-ref' },
        revealPassword: false,
        actualPassword: 'generated-password'
      })

      // Requirements 2.1, 2.2, 2.3, 2.5: Verify connection strings match expected format
      expect(result.direct.uri).toBe(`postgresql://${autoGeneratedUser}:[YOUR_PASSWORD]@localhost:5432/${autoGeneratedDatabase}`)
      
      // Verify the connection string can be parsed back correctly
      const url = new URL(result.direct.uri)
      const parsed = {
        user: url.username || undefined,
        password: url.password || undefined,
        host: url.hostname || undefined,
        port: url.port ? parseInt(url.port, 10) : undefined,
        database: url.pathname.slice(1) || undefined,
      }
      
      expect(parsed.user).toBe(autoGeneratedUser)
      expect(parsed.database).toBe(autoGeneratedDatabase)
      expect(parsed.host).toBe('localhost')
      expect(parsed.port).toBe(5432)
    })
  })
})