// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types



type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    amp?: boolean | 'hybrid' | string // necessary for JS
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type ApiRouteConfig = {
  default: (req: any, res: any) => Promise<Response | void> | Response | void
  config?: {
    api?: {
      bodyParser?: boolean | { sizeLimit?: string }
      responseLimit?: string | number | boolean
      externalResolver?: boolean
    }
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    maxDuration?: number
  }
}






// Validate ../../pages/404.tsx
{
  const handler = {} as typeof import("../../pages/404.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/500.tsx
{
  const handler = {} as typeof import("../../pages/500.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/account/audit.tsx
{
  const handler = {} as typeof import("../../pages/account/audit.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/account/me.tsx
{
  const handler = {} as typeof import("../../pages/account/me.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/account/security.tsx
{
  const handler = {} as typeof import("../../pages/account/security.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/account/tokens.tsx
{
  const handler = {} as typeof import("../../pages/account/tokens.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/admin/credential-monitoring.tsx
{
  const handler = {} as typeof import("../../pages/admin/credential-monitoring.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/authorize.tsx
{
  const handler = {} as typeof import("../../pages/authorize.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/aws-marketplace-onboarding.tsx
{
  const handler = {} as typeof import("../../pages/aws-marketplace-onboarding.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/claim-project.tsx
{
  const handler = {} as typeof import("../../pages/claim-project.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/cli/login.tsx
{
  const handler = {} as typeof import("../../pages/cli/login.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/forgot-password-mfa.tsx
{
  const handler = {} as typeof import("../../pages/forgot-password-mfa.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/forgot-password.tsx
{
  const handler = {} as typeof import("../../pages/forgot-password.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/integrations/github/authorize.tsx
{
  const handler = {} as typeof import("../../pages/integrations/github/authorize.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/integrations/vercel/[slug]/deploy-button/new-project.tsx
{
  const handler = {} as typeof import("../../pages/integrations/vercel/[slug]/deploy-button/new-project.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/integrations/vercel/[slug]/marketplace/choose-project.tsx
{
  const handler = {} as typeof import("../../pages/integrations/vercel/[slug]/marketplace/choose-project.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/integrations/vercel/install.tsx
{
  const handler = {} as typeof import("../../pages/integrations/vercel/install.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/join.tsx
{
  const handler = {} as typeof import("../../pages/join.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/logout.tsx
{
  const handler = {} as typeof import("../../pages/logout.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/maintenance.tsx
{
  const handler = {} as typeof import("../../pages/maintenance.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/new/[slug].tsx
{
  const handler = {} as typeof import("../../pages/new/[slug].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/new/index.tsx
{
  const handler = {} as typeof import("../../pages/new/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/apps.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/apps.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/audit.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/audit.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/billing.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/billing.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/documents.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/documents.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/general.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/general.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/index.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/integrations.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/integrations.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/security.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/security.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/sso.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/sso.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/team.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/team.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/[slug]/usage.tsx
{
  const handler = {} as typeof import("../../pages/org/[slug]/usage.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/_/[[...routeSlug]].tsx
{
  const handler = {} as typeof import("../../pages/org/_/[[...routeSlug]].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/org/index.tsx
{
  const handler = {} as typeof import("../../pages/org/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/organizations.tsx
{
  const handler = {} as typeof import("../../pages/organizations.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/advisors/performance.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/advisors/performance.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/advisors/rules/performance.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/advisors/rules/performance.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/advisors/rules/security.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/advisors/rules/security.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/advisors/security.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/advisors/security.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/api/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/api/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/advanced.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/advanced.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/audit-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/audit-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/hooks.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/hooks.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/mfa.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/mfa.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/oauth-apps.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/oauth-apps.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/oauth-server.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/oauth-server.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/overview.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/overview.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/policies.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/policies.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/protection.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/protection.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/providers.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/providers.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/rate-limits.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/rate-limits.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/sessions.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/sessions.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/smtp.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/smtp.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/templates/[templateId].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/templates/[templateId].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/templates/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/templates/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/third-party.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/third-party.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/url-configuration.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/url-configuration.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/auth/users.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/auth/users.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/branches/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/branches/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/branches/merge-requests.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/branches/merge-requests.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/building.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/building.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/backups/pitr.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/backups/pitr.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/backups/restore-to-new-project.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/backups/restore-to-new-project.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/backups/scheduled.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/backups/scheduled.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/column-privileges.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/column-privileges.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/etl/[pipelineId].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/etl/[pipelineId].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/etl/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/etl/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/extensions.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/extensions.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/functions.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/functions.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/indexes.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/indexes.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/migrations.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/migrations.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/publications/[id].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/publications/[id].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/publications/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/publications/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/roles.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/roles.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/schemas.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/schemas.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/settings.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/settings.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/tables/[id].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/tables/[id].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/tables/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/tables/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/triggers.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/triggers.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/database/types.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/database/types.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/editor/[id].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/editor/[id].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/editor/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/editor/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/editor/new.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/editor/new.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/[functionSlug]/code.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/[functionSlug]/code.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/[functionSlug]/details.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/[functionSlug]/details.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/[functionSlug]/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/[functionSlug]/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/[functionSlug]/invocations.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/[functionSlug]/invocations.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/[functionSlug]/logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/[functionSlug]/logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/new.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/new.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/functions/secrets.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/functions/secrets.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/integrations/[id]/[pageId]/[childId]/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/integrations/[id]/[pageId]/[childId]/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/integrations/[id]/[pageId]/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/integrations/[id]/[pageId]/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/integrations/[id]/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/integrations/[id]/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/integrations/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/integrations/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/auth-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/auth-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/cron-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/cron-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/dedicated-pooler-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/dedicated-pooler-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/edge-functions-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/edge-functions-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/edge-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/edge-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/etl-replication-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/etl-replication-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/explorer/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/explorer/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/explorer/recent.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/explorer/recent.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/explorer/saved.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/explorer/saved.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/explorer/templates.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/explorer/templates.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/pg-upgrade-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/pg-upgrade-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/pgcron-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/pgcron-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/pooler-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/pooler-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/postgres-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/postgres-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/postgrest-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/postgrest-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/realtime-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/realtime-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/logs/storage-logs.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/logs/storage-logs.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/merge.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/merge.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/[id].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/[id].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/api-overview.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/api-overview.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/auth.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/auth.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/database.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/database.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/edge-functions.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/edge-functions.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/postgrest.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/postgrest.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/query-performance.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/query-performance.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/realtime.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/realtime.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/observability/storage.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/observability/storage.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/realtime/inspector.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/realtime/inspector.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/realtime/policies.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/realtime/policies.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/realtime/settings.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/realtime/settings.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/addons.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/addons.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/api-keys/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/api-keys/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/api-keys/new.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/api-keys/new.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/api.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/api.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/billing/usage.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/billing/usage.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/compute-and-disk.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/compute-and-disk.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/general.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/general.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/infrastructure.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/infrastructure.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/integrations.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/integrations.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/jwt/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/jwt/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/jwt/signing-keys.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/jwt/signing-keys.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/settings/log-drains.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/settings/log-drains.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/sql/[id].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/sql/[id].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/sql/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/sql/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/sql/quickstarts.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/sql/quickstarts.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/sql/templates.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/sql/templates.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/analytics/buckets/[bucketId].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/analytics/buckets/[bucketId].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/analytics/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/analytics/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/files/buckets/[bucketId].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/files/buckets/[bucketId].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/files/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/files/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/files/policies.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/files/policies.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/files/settings.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/files/settings.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/s3.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/s3.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/vectors/buckets/[bucketId].tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/vectors/buckets/[bucketId].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/[ref]/storage/vectors/index.tsx
{
  const handler = {} as typeof import("../../pages/project/[ref]/storage/vectors/index.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/project/_/[[...routeSlug]].tsx
{
  const handler = {} as typeof import("../../pages/project/_/[[...routeSlug]].js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/reset-password.tsx
{
  const handler = {} as typeof import("../../pages/reset-password.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/sign-in-fly-tos.tsx
{
  const handler = {} as typeof import("../../pages/sign-in-fly-tos.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/sign-in-mfa.tsx
{
  const handler = {} as typeof import("../../pages/sign-in-mfa.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/sign-in-partner.tsx
{
  const handler = {} as typeof import("../../pages/sign-in-partner.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/sign-in-sso.tsx
{
  const handler = {} as typeof import("../../pages/sign-in-sso.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/sign-in.tsx
{
  const handler = {} as typeof import("../../pages/sign-in.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/sign-up.tsx
{
  const handler = {} as typeof import("../../pages/sign-up.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/support/link.tsx
{
  const handler = {} as typeof import("../../pages/support/link.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/support/new.tsx
{
  const handler = {} as typeof import("../../pages/support/new.js")
  handler satisfies PagesPageConfig
}

// Validate ../../pages/api/ai/code/complete.ts
{
  const handler = {} as typeof import("../../pages/api/ai/code/complete.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/docs.ts
{
  const handler = {} as typeof import("../../pages/api/ai/docs.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/feedback/classify.ts
{
  const handler = {} as typeof import("../../pages/api/ai/feedback/classify.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/feedback/rate.ts
{
  const handler = {} as typeof import("../../pages/api/ai/feedback/rate.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/onboarding/design.ts
{
  const handler = {} as typeof import("../../pages/api/ai/onboarding/design.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/sql/check-api-key.ts
{
  const handler = {} as typeof import("../../pages/api/ai/sql/check-api-key.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/sql/cron-v2.ts
{
  const handler = {} as typeof import("../../pages/api/ai/sql/cron-v2.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/sql/generate-v4.ts
{
  const handler = {} as typeof import("../../pages/api/ai/sql/generate-v4.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/sql/title-v2.ts
{
  const handler = {} as typeof import("../../pages/api/ai/sql/title-v2.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/ai/table-quickstart/generate-schemas.ts
{
  const handler = {} as typeof import("../../pages/api/ai/table-quickstart/generate-schemas.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/check-cname.ts
{
  const handler = {} as typeof import("../../pages/api/check-cname.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/cli-release-version.ts
{
  const handler = {} as typeof import("../../pages/api/cli-release-version.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/configuration-health.ts
{
  const handler = {} as typeof import("../../pages/api/configuration-health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/connect/index.ts
{
  const handler = {} as typeof import("../../pages/api/connect/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/edge-functions/test.ts
{
  const handler = {} as typeof import("../../pages/api/edge-functions/test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/generate-attachment-url.ts
{
  const handler = {} as typeof import("../../pages/api/generate-attachment-url.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/get-deployment-commit.ts
{
  const handler = {} as typeof import("../../pages/api/get-deployment-commit.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/get-ip-address.ts
{
  const handler = {} as typeof import("../../pages/api/get-ip-address.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/get-utc-time.ts
{
  const handler = {} as typeof import("../../pages/api/get-utc-time.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/health.ts
{
  const handler = {} as typeof import("../../pages/api/health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/internal/startup-init.ts
{
  const handler = {} as typeof import("../../pages/api/internal/startup-init.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/mcp/index.ts
{
  const handler = {} as typeof import("../../pages/api/mcp/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/metrics/credential-usage.ts
{
  const handler = {} as typeof import("../../pages/api/metrics/credential-usage.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/admin/initialize-service-router.ts
{
  const handler = {} as typeof import("../../pages/api/platform/admin/initialize-service-router.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/admin/repair-schemas.ts
{
  const handler = {} as typeof import("../../pages/api/platform/admin/repair-schemas.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/invite.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/invite.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/magiclink.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/magiclink.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/otp.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/otp.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/recover.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/recover.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/users/[id]/factors.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/users/[id]/factors.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/users/[id]/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/users/[id]/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/auth/[ref]/users/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/auth/[ref]/users/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/credential-monitoring/audit-log.ts
{
  const handler = {} as typeof import("../../pages/api/platform/credential-monitoring/audit-log.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/credential-monitoring/health.ts
{
  const handler = {} as typeof import("../../pages/api/platform/credential-monitoring/health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/credential-monitoring/report.ts
{
  const handler = {} as typeof import("../../pages/api/platform/credential-monitoring/report.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/credential-monitoring/stats.ts
{
  const handler = {} as typeof import("../../pages/api/platform/credential-monitoring/stats.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/database/[ref]/pooling.ts
{
  const handler = {} as typeof import("../../pages/api/platform/database/[ref]/pooling.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/integrations/[slug].ts
{
  const handler = {} as typeof import("../../pages/api/platform/integrations/[slug].js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/integrations/github/authorization.ts
{
  const handler = {} as typeof import("../../pages/api/platform/integrations/github/authorization.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/integrations/github/connections.ts
{
  const handler = {} as typeof import("../../pages/api/platform/integrations/github/connections.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/integrations/github/repositories.ts
{
  const handler = {} as typeof import("../../pages/api/platform/integrations/github/repositories.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/notifications/summary.ts
{
  const handler = {} as typeof import("../../pages/api/platform/notifications/summary.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/available-versions.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/available-versions.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/billing/invoices.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/billing/invoices.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/billing/invoices/upcoming.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/billing/invoices/upcoming.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/billing/plans.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/billing/plans.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/billing/subscription.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/billing/subscription.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/members/reached-free-project-limit.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/members/reached-free-project-limit.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/oauth/apps.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/oauth/apps.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/payments.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/payments.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/projects.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/projects.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/[slug]/tax-ids.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/[slug]/tax-ids.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/organizations/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/organizations/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/column-privileges.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/column-privileges.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/extensions.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/extensions.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/foreign-tables.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/foreign-tables.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/materialized-views.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/materialized-views.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/policies.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/policies.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/publications.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/publications.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/query/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/query/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/tables.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/tables.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/triggers.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/triggers.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/types.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/types.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/pg-meta/[ref]/views.ts
{
  const handler = {} as typeof import("../../pages/api/platform/pg-meta/[ref]/views.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/profile/audit-login.ts
{
  const handler = {} as typeof import("../../pages/api/platform/profile/audit-login.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/profile/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/profile/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/profile/permissions.ts
{
  const handler = {} as typeof import("../../pages/api/platform/profile/permissions.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects-resource-warnings.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects-resource-warnings.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/__tests__/advisor.test.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/__tests__/advisor.test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/__tests__/logs.test.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/__tests__/logs.test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/__tests__/monitoring.test.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/__tests__/monitoring.test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/__tests__/supavisor-config-integration.test.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/__tests__/supavisor-config-integration.test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/advisor.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/advisor.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/analytics/endpoints/[name].ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/analytics/endpoints/[name].js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/analytics/log-drains.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/analytics/log-drains.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/analytics/log-drains/[uuid].ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/analytics/log-drains/[uuid].js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/api-keys/temporary.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/api-keys/temporary.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/api/graphql.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/api/graphql.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/api/rest.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/api/rest.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/billing/addons.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/billing/addons.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/config/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/config/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/config/postgrest.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/config/postgrest.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/content/count.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/content/count.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/content/folders/[id].ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/content/folders/[id].js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/content/folders/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/content/folders/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/content/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/content/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/content/item/[id].ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/content/item/[id].js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/databases.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/databases.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/docker-containers.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/docker-containers.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/infra-monitoring.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/infra-monitoring.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/logs.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/logs.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/monitoring.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/monitoring.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/password.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/password.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/run-lints.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/run-lints.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/service-config.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/service-config.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/settings.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/settings.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/supavisor-config-management.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/supavisor-config-management.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/supavisor-config.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/supavisor-config.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/supavisor-health.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/supavisor-health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/supavisor-recommendations.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/supavisor-recommendations.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/[ref]/supavisor-stats.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/[ref]/supavisor-stats.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/__tests__/create.test.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/__tests__/create.test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/__tests__/index.test.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/__tests__/index.test.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/available-regions.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/available-regions.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/create.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/create.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/projects/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/projects/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/props/org/[slug].tsx
{
  const handler = {} as typeof import("../../pages/api/platform/props/org/[slug].js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/props/project/[ref]/api.ts
{
  const handler = {} as typeof import("../../pages/api/platform/props/project/[ref]/api.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/props/project/[ref]/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/props/project/[ref]/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/service-config/health.ts
{
  const handler = {} as typeof import("../../pages/api/platform/service-config/health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/service-config/stats.ts
{
  const handler = {} as typeof import("../../pages/api/platform/service-config/stats.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/signin.ts
{
  const handler = {} as typeof import("../../pages/api/platform/signin.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/signup.ts
{
  const handler = {} as typeof import("../../pages/api/platform/signup.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/empty.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/empty.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/objects/download.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/objects/download.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/objects/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/objects/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/objects/list.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/objects/list.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/objects/move.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/objects/move.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/objects/public-url.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/objects/public-url.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/[id]/objects/sign.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/[id]/objects/sign.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/storage/[ref]/buckets/index.ts
{
  const handler = {} as typeof import("../../pages/api/platform/storage/[ref]/buckets/index.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/stripe/invoices/overdue.ts
{
  const handler = {} as typeof import("../../pages/api/platform/stripe/invoices/overdue.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/telemetry/event.ts
{
  const handler = {} as typeof import("../../pages/api/platform/telemetry/event.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/platform/telemetry/feature-flags.ts
{
  const handler = {} as typeof import("../../pages/api/platform/telemetry/feature-flags.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/runtime-config.ts
{
  const handler = {} as typeof import("../../pages/api/runtime-config.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/system-health.ts
{
  const handler = {} as typeof import("../../pages/api/system-health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/api-keys.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/api-keys.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/branches.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/branches.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/database/migrations.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/database/migrations.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/health.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/health.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/network-bans.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/network-bans.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/network-bans/retrieve.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/network-bans/retrieve.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/network-restrictions.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/network-restrictions.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/network-restrictions/apply.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/network-restrictions/apply.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/ssl-enforcement.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/ssl-enforcement.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/types/typescript.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/types/typescript.js")
  handler satisfies ApiRouteConfig
}

// Validate ../../pages/api/v1/projects/[ref]/upgrade/status.ts
{
  const handler = {} as typeof import("../../pages/api/v1/projects/[ref]/upgrade/status.js")
  handler satisfies ApiRouteConfig
}


